FROM mcr.microsoft.com/devcontainers/base:debian
RUN sudo apt-get update && \
    sudo apt-get install -y \
    libwebkit2gtk-4.0-dev \
    build-essential \
    libssl-dev \
    libgtk-3-dev \
    libayatana-appindicator3-dev \
    librsvg2-dev
